ktor:
    application:
        modules:
            - LucasWithBoots.github.io.ApplicationKt.module
    deployment:
        port: 8080
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/pontoQR"
    user: "postgres"
    password: "senha"
jwt:
    secret: "secret"
    issuer : "http://0.0.0.0:8080/"
    audience: "http://0.0.0.0:8080/hello"
    realm: "Access to 'hello'"
}