ktor:
    application:
        modules:
            - LucasWithBoots.github.io.ApplicationKt.module
    deployment:
        port: 8080
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/pontoQR"
    user: "postgres"
    password: "senha"